### ISSUE TITLE
Mint DOIs for Datasets with Handles in dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#4] opened 2019-02-06 22:35 UTC
We have this endpoint: 

http://guides.dataverse.org/en/latest/admin/dataverses-datasets.html#mint-new-pid-for-a-dataset

We should use it to mint DOIs for datasets in dataverse.harvard.edu with Handles in support of Make Data Count in #4821.

**Comment by djbrooke** [comment] 2019-04-02 14:51
When 4.12 (contains the fix for #5559) is on prod, we can finish this up.

**Comment by landreev** [comment] 2019-05-20 22:15
Started a new batch job for the still un-converted handle-ed datasets earlier today.

**Comment by landreev** [comment] 2019-05-21 21:16
Of the 4225 datasets that still had handles, only 5 are still failing to obtain a DOI: 
```
1902.1/01957
1902.1/10344
1902.1/10766
1902.1/11748
1902.1/12641
```

**Comment by landreev** [comment] 2019-05-22 15:12
Confirming that the published files in the newly-DOI assigned datasets have been registered as well (~12K files total).

**Comment by djbrooke** [comment] 2019-05-22 15:42
@jggautier and I are checking:

- [ ] 1902.1/01957
- [ ] 1902.1/10344
- [ ] 1902.1/10766
- [ ] 1902.1/11748
- [ ] 1902.1/12641

**Comment by landreev** [comment] 2019-05-22 15:43
The remaining 5 handle-ed datasets, with the database ids:
```
1902.1/01957	48340
1902.1/10344	61008
1902.1/10766	2669292
1902.1/11748	54917
1902.1/12641	56380
```
Note that all 5 pass the validation API - so it's not the constraint violations; so the objects are valid, from our point of view - it's something that's specifically needed for Datacite registration that's missing, probably (?). 

Interestingly, 1902.1	/11748 is not even published. Meaning, we shouldn't even be trying to actually register the new identifier with Datacite... the whole process must be failing at an earlier stage somewhere, somehow.

**Comment by landreev** [comment] 2019-05-22 16:13
What's interesting is that even though the datasets do pass the constraint validation API, I'm seeing this in the exception stack trace when attempting to register 54917:
```
Caused by: javax.persistence.PersistenceException: javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.
```
Also this:
```
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.search.IndexServiceBean.addOrUpdateDataset(IndexServiceBean.java:1046)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(IndexServiceBean.java:423)
```
1046 is a fairly innocent-looking line though:
```
 datafileSolrInputDocument.addField(SearchFields.METADATA_SOURCE, findRootDataverseCached().getName());
```
so basically I'm out of ideas really... but maybe just looking at the dataset and the metadata for any obvious weirdness is the best way to go...

**Comment by jggautier** [comment] 2019-05-22 16:32
Is the DataCite xml metadata that Dataverse exports (that you can get through the UI in the Metadata tab) the same xml that is sent to DataCite for registering DOIs?

If it is, then the problem with 1902.1/01957 might be that the DataCite metadata export fails xml validation, because of this part:
```
<contributors>
<contributor contributorType="Producer">
<contributorName/>
</contributor>
</contributors>
```

In the Producer compound field, the Producer name field has no value, so there should be no contributorName for that contributorType. But the Producer URL field does have a value (a valid URL). When I try on Demo Dataverse to create a dataset, or create a new dataset version, where I add a Producer URL but do not add a Producer name, the dataset creation fails and shows this error message:

> Error – This dataset may not be published due to an error when contacting the DataCite Service. Please try again. If you believe this is an error, please contact Demo Dataverse Support for assistance.

One thing we could do is either publish a new minor dataset version and a Producer Name or remove the Producer URL. Then see if we can register a DOI for that dataset. We'd need permission from the dataset owners.

The other four datasets don't have this problem: They have no values in any of the Producer fields. The DataCite xml export from these four datasets validate.

All five datasets do have some metadata in the Distributor field, but that isn't mapped to any DataCite property.

**Comment by djbrooke** [comment] 2019-05-22 19:18
Thanks @jggautier for the investigation!

**Comment by pdurbin** [comment] 2019-05-22 19:29
> Is the DataCite xml metadata that Dataverse exports (that you can get through the UI in the Metadata tab) the same xml that is sent to DataCite for registering DOIs?

I **think** both derive from https://github.com/IQSS/dataverse/blob/v4.14/src/main/resources/edu/harvard/iq/dataverse/datacite_metadata_template.xml but @sekmiller or others would probably know for sure.

**Comment by scolapasta** [comment] 2019-05-29 17:54
For ```1902.1/01957``` @jggautier can you contact the dataset owner and see if you can get the needed info?

For   ```1902.1/11748``` should we just change manually on the backend to a doi? and if they ever publish it would work normally?

I'm not sure what to suggest for the other 3.

**Comment by jggautier** [comment] 2019-05-29 18:20
> For 1902.1/01957 @jggautier can you contact the dataset owner and see if you can get the needed info?

I got the okay from @sbarbosadataverse and I removed the metadata in the producer fields. I also added a subject since it didn't have one. I created a draft version, but I'm not able to publish it. I get the blue spinning graphic and then nothing happens. It's still in draft state.

I just noticed that the other four datasets are missing subject metadata, too - not a requirement for DataCite but is a requirement for creating datasets in Dataverse.

**Comment by jggautier** [comment] 2019-05-31 16:10
A new version of the dataset [1902.1/01957](https://hdl.handle.net/1902.1/01957) is now published with the producer fields removed. @landreev, could you try again to register a DOI for this dataset?

Some of the datasets are missing either a Contact Name or Contact Email. DataCite doesn't require either of these, but
- Dataverse does require a Contact Email to create datasets. I'm guessing these datasets were published before a Contact Email was a requirement.
- Dataverse NO repository had an issue with trying to register DOIs for datasets that didn't have a Contact Name (https://github.com/IQSS/dataverse/issues/3839).

Not sure if this missing metadata is the culprit. [1902.1/01957](https://hdl.handle.net/1902.1/01957) has no Contact Name. If it's able to get a DOI, then the missing Contact Name isn't the problem.

**Comment by pdurbin** [comment] 2019-05-31 16:43
> Dataverse does require a Contact Email to create datasets. I'm guessing these datasets were published before a Contact Email was a requirement.

@jggautier as you know, I'm of the opinion that we should simply make Contact Email a required field. EZID didn't require it but DataCite does. It would be a fix for https://github.com/IQSS/dataverse/issues/3839 (thanks for linking to that issue above).

**Comment by jggautier** [comment] 2019-05-31 17:53
Do you mean you think we should make Contact Name a required field? (Dataverse already requires a Contact Email.)

How can I tell that DataCite requires Contact Name (or Contact Email)? None of [the DataCite schema documentation](https://schema.datacite.org/) lists those as required fields.

**Comment by pdurbin** [comment] 2019-05-31 18:05
@jggautier bah! Sorry, I meant Contact Name. The easiest way to exercise the bug is to simply delete the Contact Name (which is auto populated) and try to publish the dataset. I just tried this on the demo site and I was a little surprised to see that it published just fine. Since you have a superuser account maybe you could try this in production and "destroy" the dataset afterwards. Basically, I wondering if https://github.com/IQSS/dataverse/issues/3839 is still a bug or not. It's hard to tell from the demo site.

**Comment by jggautier** [comment] 2019-05-31 21:40
@pdurbin I published a dataset on Harvard Dataverse without Contact Name metadata. I had to delete it, but I'm sure other real datasets have been published without a Contact Name, too. To be honest, I only brought this bug up in this issue on chance that it might somehow be related (feels like I'm grasping at straws).

**Comment by scolapasta** [comment] 2019-06-25 20:29
I reran the API for 1902.1/01957 and it now has a DOI. The others will take more investigation.

**Comment by scolapasta** [comment] 2019-07-16 02:39
I figured it out!

The issue is that the name column for datavariables is null (well '').

This query:
select df.owner_id, df.id, count(*) 
from dvobject df, datatable dt, datavariable dv 
where df.id=dt.datafile_id 
and dt.id=dv.datatable_id and dv.name =''
group by df.owner_id, df.id order by df.owner_id;

returns 7 files, all of which belong the the 4 datasets above.

**Comment by scolapasta** [comment] 2019-07-16 02:41
So, todos:
1. Decide what to do with these - is there a name we can give each variable? If not should we "uningest" and possibly reingest these files (will this affect the UNF for the published ones?)

2. Before we fix, we may want to update our admin validator code to get files for each dataset and variables. (though that may make the one thar runs on the whole db take significantly longer. 

Let's discuss this week either after standup or at backlog grooming.

**Comment by djbrooke** [comment] 2019-07-16 15:37
1. Give a generic variable name (this will allow us to successfully mint DOIs and implement Make Data Count in Harvard Dataverse)
2. Extend validation API to optionally validate down to the variable level (issue incoming)

**Comment by landreev** [comment] 2019-07-19 21:51
OK, the affected variables have been given names of the type "varNN" where NN is the variable order in the datatable.

**Comment by landreev** [comment] 2019-07-19 22:14
Finally, the last 4 handle datasets have been assigned DOIs. 
The datasets:

DBID | Handle | DOI
----- | ------- | ----
61008	| 1902.1/10344 | 10.7910/DVN/8ZSDCH
2669292	| 1902.1/10766 | 10.7910/DVN/SIWH9F
54917	| 1902.1/11748 | 10.7910/DVN/E4TERD
56380	| 1902.1/12641 | 10.7910/DVN/AULYGY

@scolapasta I'm moving this straight to QA, since there's nothing to review. 
@kcondon I guess the only QA left for this is to verify that there are no datasets left with handles for the primary identifier.

**Comment by kcondon** [comment] 2019-07-22 18:08
Checked dvobject table for non-dois, all clear. Also eyeballed alternativepersistentidentifier table.

**Closed by kcondon** 2019-07-22 18:08 UTC
Labels: Medium
