### ISSUE TITLE
Account notifications in production: site should not time out with minimal notifications 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#91] opened 2020-11-12 17:45 UTC
I have 11 notification in my account on production, and when I try to access them, it times out "dataverse taking  long to respond"

**Comment by scolapasta** [comment] 2020-11-12 17:50
@sbarbosadataverse when you say you have 11 notifications, is that what you see near your icon? if so, then my guess is you have 11 new notifications, but some especially large number of old ones. If so, then this is a duplicate of:
https://github.com/IQSS/dataverse/issues/2892

As a workaround until we fix this, we could delete some of your older notifications. Let me know your username and we can see how many are there.

**Closed** 2020-11-16 17:05 UTC
Labels: bug
