### ISSUE TITLE
Spike. Unpublished datasets and some published datasets with missing files have file download counts

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#179] opened 2022-07-28 22:46 UTC
Download counts should be displayed in the UI and recorded in the database (and retrievable with the Metrics API) only for published datasets that have files.

**Unpublished datasets with download counts**
But hundreds of unpublished datasets in the Harvard Dataverse Repository have file download counts, such as https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG and https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29862.

The guestbookresponse table contains entries for over 500 unpublished datasets.

<details>
  <summary>I used this query to find these datasets:</summary>

```
select
	concat('https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/', dvobject.identifier) as dataset_url,
	dataverse.name as dataverse_collection_name, 
	dvobject.createdate as dataset_creation_date,
	count(*) as file_download_count
from guestbookresponse
join dvobject on dvobject.id = guestbookresponse.dataset_id
join dataset on dataset.id = dvobject.id
join dataverse on dataverse.id = dvobject.owner_id
where
	dataset.harvestingclient_id is null and
	dvobject.publicationdate is null
group by
	dvobject.identifier,
	dvobject.createdate,
	dataverse.name
```
</details>

Most were created in 2015 and earlier, [but one](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG) was created in 2021.

**Published datasets with files but with download counts recorded before datasets were published**
About 363 datasets published with files have some of their download counts recorded before the datasets were published.

<details>
  <summary>I used this query to find these datasets:</summary>

```
with
	total_count as(
		select
			dvobject.identifier as dataset_identifier,
			count(*) as count
		from guestbookresponse
		join dvobject on dvobject.id = guestbookresponse.dataset_id
		join dataset on dataset.id = dvobject.id
		where
			dataset.harvestingclient_id is null and
			dvobject.publicationdate is not null 
		group by
			dvobject.identifier
	),
	count_before_publication as(
		select
			dvobject.identifier as dataset_identifier,
 			dataverse.name as dataverse_collection_name,
  			dvobject.publicationdate as dataset_publication_date,
			min(guestbookresponse.responsetime) as first_download_date,
			count(*) as count
		from guestbookresponse
		join dvobject on dvobject.id = guestbookresponse.dataset_id
		join dataset on dataset.id = dvobject.id
		join dataverse on dataverse.id = dvobject.owner_id
		where
			dataset.harvestingclient_id is null and
			dvobject.publicationdate is not null and 
			guestbookresponse.responsetime < dvobject.publicationdate
		group by
			dvobject.identifier,
			dvobject.publicationdate,
			dataverse.name
	)
select
	concat('https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/', count_before_publication.dataset_identifier) as dataset_url,
	count_before_publication.dataverse_collection_name,
	count_before_publication.first_download_date,
	count_before_publication.dataset_publication_date,
	count_before_publication.count as count_before_publication,
	total_count.count as total_count
from count_before_publication
join total_count on total_count.dataset_identifier = count_before_publication.dataset_identifier
order by count_before_publication.count desc
```
</details>

**Published datasets with missing files that have download counts**
Datasets affected by the bug described in https://github.com/IQSS/dataverse/issues/8867 have files with download counts that don't appear on the datasets' pages. The effect is easier to spot for the dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H8OFUY, which has no files shown on the page but the page is showing download counts. Other datasets that I think are affected by this bug do have files showing on their pages but it looks like some of these datasets' files with download counts are not shown on the pages.

<details>
<summary>I used this query to find these datasets:</summary>

```
with
	files_with_no_owner_id as(
		select dvobject.id as file_id
		from dvobject
		where dvobject.owner_id is null and dtype = 'DataFile'
	)
select distinct dvobject.identifier as dataset_identifier
from guestbookresponse
join files_with_no_owner_id on files_with_no_owner_id.file_id = guestbookresponse.datafile_id
join dvobject on dvobject.id = guestbookresponse.dataset_id
```

</details>

This is concerning because it might confuse depositors and curators, and it inflates download counts, used as evidence of data re-use.

**Comment by mreekie** [comment] 2022-08-01 18:28
Gustavo discussed with Julian.

**Comment by mreekie** [comment] 2022-08-03 18:35
Leonid - this could be a side effect of a different 5.11 bug. Leonid has a list of fixed identifiers.  At least one of the datasets mentioned is one that was mentioned during the standup. 
Jim - back in history - there may have been a time when previewers were triggering a count, even when just previewing? 
Phil - when use a tool to increment the count, the tool name should be included in the database so we can identify this.

**Comment by mreekie** [comment] 2022-08-03 18:38
We will timebox this to the sprint.
If it requires more than this sprint to fix we'll regroup with what was learned.

**Comment by mreekie** [comment] 2022-08-03 18:39
Leonid - we shoudl timebox this as no more than a little bit of time.  We should not invest too much time in root cause.
Gustavo - Let's call it a medium

**Comment by landreev** [comment] 2022-08-17 22:32
Almost all of the unpublished datasets with registered counts are in fact very old legacy - pre-Dataverse, i.e. DVN migrations. It just means that we used to count downloads on drafts (from authors/admins) back then - so yes, a legacy issue. 

The one exception, the more recent dataset:  
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG - it appears that it was published at some point; there must have been some reason why we had to un-publish it by force. So the downloads on this one must have been normal downloads that just happened during the window when it was publicly available. There are only 8 guestbookresponse records; and only 3 of them are from a non-IFPRI user. I would preserve them just in case; if there was a good reason why we had to unpublish the dataset, I would assume there's some non-zero chance somebody may be interested to know who downloaded the files from it, and which ones.

**Comment by landreev** [comment] 2022-08-17 22:35
As for the 500+ unpublished datasets that have these legacy download counts - anyone has a problem with me just erasing the response records for these? There are only ~13K of these total.

**Comment by jggautier** [comment] 2022-08-18 15:01
Thanks @landreev! 

Hmmm, one of the two datasets I linked is from IFPRI, that dataset appears in their collection's guestbook, and they're always interested in download counts. I can see how many of those 13k downloads belong to datasets in the IFPRI collections. It might be good to let them know that download counts will go down.

Pinging @sbarbosadataverse. I'm not aware of any other collections as interested in download counts as the IFPRI group is but maybe Sonia knows?

**Comment by jggautier** [comment] 2022-08-18 15:58
Most of the datasets are either in https://dataverse.harvard.edu/dataverse/rtownsend or in the Graduate School of Design Dataverse at https://dataverse.harvard.edu/dataverse/platform7. 

I don't think the depositor of https://dataverse.harvard.edu/dataverse/rtownsend is checking their download counts.

And the Graduate School of Design Dataverse is unpublished, so I think it would be fine to remove those counts.

That [one IFPRI dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG) is the only dataset in the IFPRI collections, at least as far as I can tell from the queries I posted.

The rest of the datasets are in Dataverse collections where I don't think counts are being monitored and where I think the depositors wouldn't care or even notice that counts in their guestbooks went down.

**Comment by landreev** [comment] 2022-08-18 17:36
Yes, the IFPRI dataset ([VO8EYG](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG)) is the one that I mentioned as being an exception; I suggested that we keep the guestbookresponse records for that one. The other ones are all more ancient legacy and the guestbookresponses for them should be safe to remove.

**Comment by landreev** [comment] 2022-08-31 22:32
Yes, the IFPRI dataset ([VO8EYG](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG)) is the one that I mentioned as being an exception; I suggested that we keep the guestbookresponse records for that one. The other ones are all more ancient legacy and the guestbookresponses for them should be safe to remove.

**Comment by landreev** [comment] 2022-08-31 23:17
All the 13K+ download counts/guestbookresponses from the unpublished datasets above have been deleted (with the exception of one tricky dataset [VO8EYG](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VO8EYG) as described above). 

But, do we want to do the same thing with the responses in published datasets that had been recorded prior to the publication date? (Your 2nd query above). There appears to be only ~3K of these, in 363 datasets total. Just like with the first group, most of these are obvious legacy (pre-Dataverse 4), with a few exceptions recorded more recently.

**Comment by jggautier** [comment] 2022-09-01 16:46
Yeah I think it would be good to also remove the responses in published datasets that had been recorded prior to the publication date. Considering the two IFPRI datasets among them, the downloads that would be removed are a small fraction of the dataset's total downloads. Very small changes:

<img width="1070" alt="Screen Shot 2022-09-01 at 12 42 59 PM" src="https://user-images.githubusercontent.com/18374574/187967946-8382d069-b656-4d07-95e4-2881703e3674.png">

I haven't heard from @sbarbosadataverse about this issue. Have you @landreev? I could ping her on Slack when she gets back next Tuesday.

**Comment by landreev** [comment] 2022-09-01 20:37
I feel like it makes sense to just go ahead and delete this. As you said, it is negligible number of downloads in question. 
I'll preserve the entries, just in case, but seems like a pretty non-controversial thing to do. 
Thanks.

**Comment by landreev** [comment] 2022-09-01 21:03
OK, deleted. 
Which probably means we can close this issue (?).
But we should continue monitoring for this going forward; if we encounter any download counts on something again, it may be worth trying to figure out where they are coming from.

**Closed** 2022-09-06 15:48 UTC
Labels: sz.Medium, pm.Gustavo
