### ISSUE TITLE
Deploy "computational workflow" metadata block in prod. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#197] opened 2022-10-31 18:54 UTC
This is for the Harvard Data Commons collab.

**Comment by landreev** [comment] 2022-10-31 21:38
ok, done  - but please let me know if this block needs to be installed on demo as well.

**Comment by pdurbin** [comment] 2022-11-02 13:33
@landreev I'm not sure if I have a vote but yes, I think it would be nice to have the new computational workflow block on demo as well.

**Comment by cmbz** [comment] 2022-11-02 14:03
Adding my vote, too! It would be helpful for testing (I think there are some upcoming use cases for it) and for promoting the new feature.

**Comment by sbarbosadataverse** [comment] 2022-11-07 19:16
@landreev Adding this to demo is fine. This request is in Harvard dataverse github and not sure it should be?

**Comment by pdurbin** [comment] 2023-05-17 20:22
I can confirm that the Computational Workflow metadata block is available in Harvard Dataverse. It's not in demo. Perhaps we should make a decision about demo before closing.

**Comment by jggautier** [comment] 2023-07-10 17:47
Is it fair to say that a decision about putting this metadatablock on Demo hasn't been made because plans to test the metadatablock are still being hashed out? If so, could this issue be closed, and then when plans for testing are settled, we can open a new GitHub issue about adding the metadatablock to Demo?

**Comment by cmbz** [comment] 2023-07-10 17:55
@jggautier One point in favor of deploying the metadata block on demo before testing is that having it available on demo means that we can demonstrate the feature in presentations and to folks who may be interested. At present, it's difficult to do this on HDV since you need to have a published collection that uses the metadata block. As a result, I wasn't able to demo the feature at the NIH GREI meeting in May.

**Comment by sbarbosadataverse** [comment] 2024-05-15 20:07
opened ticket for adding block to demo: https://github.com/IQSS/dataverse.harvard.edu/issues/273
closing this one

**Closed by sbarbosadataverse** 2024-05-15 20:07 UTC
